### ISSUE TITLE
Correct place for TypoScript extension configuration

### ISSUE THREAD

**Issue by responseinformationsdesign** [typo3-themes/theme_bootstrap#47]
Where is the correct place to put TypoScript code for extension configuration?
Some TypoScript is put in Configuration > TypoScript > Library (f.e. plugin.realurl.setupts), other is located in Resources > Private > Extensions > <ExtensionName> > TypoScript (f. e. for extension News).

Thanks in advance,
Gerhard

**Comment by tdeuling** [comment]
Hi,
the realurl.setupts is located in Confiugration/Library, because it's most often required and it's the only file you need of this extension. In other cases, when you have some more files, like templates and so on, place this files in a Resources/Private/ExtensionKey/ folder, in order to get a encapsulated area for this files.
