### ISSUE TITLE
Container and row element not working - FSC - TYPO3 7.6

### ISSUE THREAD

**Issue by Shade634** [typo3-themes/theme_bootstrap#49]
The container and row gridelements dont work at all using FSC.
See screenshots for more info

![schermafbeelding 2016-11-15 om 11 10 31](https://cloud.githubusercontent.com/assets/6287426/20301702/a6865f20-ab24-11e6-8b80-773219b7bb49.png)
![schermafbeelding 2016-11-15 om 11 10 56](https://cloud.githubusercontent.com/assets/6287426/20301703/a6898fe2-ab24-11e6-9ae8-372407d72175.png)
![schermafbeelding 2016-11-15 om 11 12 50](https://cloud.githubusercontent.com/assets/6287426/20301704/a68de380-ab24-11e6-8ae1-12330bc1c7af.png)

**Comment by Shade634** [comment]
Sadly my typoscript knowledge lacks a bit.

but the 
`lib.gridelements {
	container < .defaultGridSetup
	container {
		stdWrap.prepend =< lib.containerBackgroundImage
		columns.0 {
			renderObj >
			renderObj = < tt_content
		}
	}
}
`

Makes me wonder on what the stdWrap.prepend works.

i have solved this a different way for a non theme related project with:
`container < lib.gridelements.defaultGridSetup
	container {
		cObject = FLUIDTEMPLATE
		cObject {
			file = EXT:###_###/Resources/Private/Partials/Gridelements/Section.html
		}
	}`

**Comment by Bunnyfield** [comment]
You should not use theme_bootstrap with FSC but go for theme_bootstrap4 instead, since theme_bootstrap is based on CSC TypoScript which is not available in FSC anymore.

There is a whole bunch of FSC compatible stuff available, but since this is the more modern approach it uses the more modern Bootstrap version as well. So expect most of the Bootstrap 4 related themes and theme bases to be working with FSC.
