### ISSUE TITLE
Sorting in listview is not recognized for the order of child elements in tab-containers

### ISSUE THREAD

**Issue by responseinformationsdesign** [typo3-themes/theme_bootstrap#51]
The sorting in tab-containers does not recognize the sorting of the elements in the list view. If using the arrows in listview for rearranging the elements these can even get lost (in listview)!

**Comment by kaystrobach** [comment]
Please provide the following information:

* TYPO3 version
* gridelements version
* theme* versions

I think it is a known gridelements behaviuor but maybe @bunnyfield takes a look

**Comment by responseinformationsdesign** [comment]
- TYPO3: 7.6.15
- PHP: 7.0.14
- gridelements: 7.0.6-dev (because of https://forge.typo3.org/issues/75249)
- themes: 7.0.3
- themes_gridelements: 7.0.1
- theme_bootstrap: 7.0.1

**Comment by Bunnyfield** [comment]
Did you set the checkbox in the gridelements configuration within the extension manager to enable element nesting for the list module? If so, it should not be possible to have lost elements by sorting them, since elements then can be sorted within their specific page or gridelements column only. Usually the sorting should be respected in the frontend output as well.

Without the list module nesting, there is no specific sorting of elements in the list. Still they can be sorted somehow. So you might get weird and unexpected results, since elements of different columns can be mixed up easily then.

**Comment by responseinformationsdesign** [comment]
Nesting is enabled. Clicking the arrows in list view doesn´t change anything. Sorting of elements in the frontend goes along with page view.

**Comment by Bunnyfield** [comment]
Just to clarify the behaviour: With nesting enabled, the list view arrows do nothing and without enabling it, you can "sort" elements to unexpected positions?

**Comment by responseinformationsdesign** [comment]
Unexspected beaviour was also with nesting enabled. But for the moment I can´t reproduce this.
Also to mention: In list view the first nested element has no arrows for sorting.

**Comment by Bunnyfield** [comment]
OK - so some things might be broken then. Could you file a bug report here https://forge.typo3.org/projects/extension-gridelements2/issues ?

**Comment by responseinformationsdesign** [comment]
https://forge.typo3.org/issues/79979

**Comment by kaystrobach** [comment]
i close it here in favour of the gridelements ticket
